#!/bin/bash
#
#Make a bet

token=`cat token`

curl -X POST --data "amount=$1&target=$2&condition=$3" https://api.primedice.com/api/bet?api_key=$token  2>/dev/null | sed -e 's/.*"win":\(true\|false\).*/\1/'
