#!/bin/bash
#
#Labouchere Bet Style

wonBet() {
local tempArray=("$@")
unset area
if [ ${#tempArray[*]} -lt 2 ]
then
unset tempArray
else
unset tempArray[0]
unset tempArray[${#tempArray[@]}]
fi
area=(${tempArray[@]})
}

id=$1

area[0]=2
area[1]=3
area[2]=3
area[3]=2
echo "Line: ${area[@]}"
while [ ${#area[@]} -gt 0 ]
do
#echo ${#area[@]}
if [ ${#area[@]} -gt 1 ]
then
let bet=${area[0]}+${area[${#area[@]}-1]}
else
bet=${area[0]}
fi
echo "Betting $bet"
won=`./bet $bet 49.5 "<"`
if [ "$won" == "true" ]
then
wonBet ${area[@]}
echo "Won!"
elif [ "$won" == "false" ]
then
declare -i area[${#area[@]}]
area[${#area[*]}]=$bet
echo "Loss!"
elif [ "$won" == "Insufficient funds" ]
then
echo "Insufficient funds!"
kill $id
exit
elif [ "$won" == "Unauthorized" ]
then
echo "Unauthorized! Check your token file and make sure it's correct!"
kill $id
exit
else
echo "An unknown error occured!"
kill $id
exit
fi
echo
echo "Line: ${area[@]}"
sleep 0.5
done
